### ISSUE TITLE
Step 2 does not work as-is without load balancer

### ISSUE THREAD

**Issue by aedocw** [IBM/microservices-traffic-management-using-istio#34]
Step 2, if you expect to use NodePort yields:
$ kubectl apply -f <(istioctl kube-inject -f bookinfo.yaml)
deployment "productpage-v1" configured
ingress "gateway" configured
The Service "productpage" is invalid: spec.ports[0].nodePort: Invalid value: 31490: may not be used when `type` is 'ClusterIP'

If bookinfo.yaml is modified to include "type: NodePort" in the productpage spec section, this step works.  Documentation should include some mention of this.

**Comment by AnthonyAmanse** [comment]
#37 Part A should've been done in the root directory of the Istio release and not this repo. The files in this repo are for Part B

**Comment by AnthonyAmanse** [comment]
Fixed in #39 to #42 PRs. The yaml file that should've been used is in the istio release directory
