### ISSUE TITLE
Step 2 instructions incomplete

### ISSUE THREAD

**Issue by aedocw** [IBM/microservices-traffic-management-using-istio#35]
Step 2 instructions tell user to do:
$ kubectl apply -f <(istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml)
which will deploy the productpage pod, but then assumes more services will be deployed:
"The microservices are productpage, details, ratings, and reviews. Note that you'll have three versions of the reviews microservice."

The bookinfo.yaml included in this repository is a clone of the one found at https://github.com/istio/istio/tree/master/samples/apps/bookinfo though this copy is incomplete.

**Comment by AnthonyAmanse** [comment]
#37 Part A should've been done in the root directory of the Istio release and not this repo. The files in this repo are for Part B thus the difference in the yaml files

**Comment by animeshsingh** [comment]
Done
