### ISSUE TITLE
"istioctl mixer rule create method" for configuring Mixer is removed in favor of kubectl

### ISSUE THREAD

**Issue by sebastiansutter** [IBM/microservices-traffic-management-using-istio#61]
I downloaded the latest version of istioctl ($ istioctl version Version: 0.5.1, GitRevision: 30acfe6528107ea333543309095659b93364b30d)
Entering istioctl mixer rule create returns:
Error: this method of configuring Mixer is removed in favor of kubectl

Can you update the tutorial to work with kubectl for creating these rules?

**Comment by loafyloaf** [comment]
fixed by #80
